### ISSUE TITLE
disjoint union type ?

### ISSUE THREAD

**Issue by depify** [jpcs/data.xq#1]
thx for the library, its been fun and instructional.

question - its unclear how one would achieve a disjoint union type ?

thx for your patience from this humble follower

**Comment by jpcs** [comment]
You mean like an enumeration? You just define a type which has sub-types with no value, ie:

``` xml
 <TriBool>
   <False/>
   <Maybe/>
   <True/>
 </TriBool>
```

**Comment by xquery** [comment]
ah, missed your answer .... yes, this works for me thanks!
